### ISSUE TITLE
Discord embed don't work

### ISSUE THREAD

**Issue by rayhanstewart** [Howard-Codes/Howard-Codes.github.io#4]
The discord embed (on the /github page after you click to join github on the main page) doesn't work on most browsers.

**Comment by aheike05** [comment]
why are you trying to embed discord? isn't that a big security problem?

**Comment by rayhanstewart** [comment]
lol yeah ur right i wasnt thinking im just gonna use the discord server embed they offer @aheike05

**Comment by rayhanstewart** [comment]
OK we fix w new branch
